<a href="https://colab.research.google.com/github/Amitkumardas123/Data-Analysis-Visualization-of-Bird-Strikes-between-2000-2011/blob/main/Data_Visualization_of_Bird_Strikes_between_2000_%E2%80%93_2011.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Project Name**    - **Data Visualization of Bird Strikes between 2000 – 2011**

##### **Project Type**    - EDA
##### **Contribution**    - Individual
##### **Name** - Amit Kumar Das

# **Project Summary -**

# The purpose of the analysis:

The purpose of this analysis is to comprehensively understand and address the critical issue of bird strikes in the aviation sector, with a specific focus on the United States. By examining data collected by the Federal Aviation Administration (FAA) from 2000 to 2011, this analysis aims to identify trends, risk factors, and potential vulnerabilities associated with bird strikes.

**`Key objectives include:`**

***1.Enhancing Aircraft Safety:***

By identifying when and where bird strikes are most likely to occur, as well as understanding the phases of flight most susceptible to these incidents, the analysis seeks to inform strategies that can mitigate the risk and enhance overall aircraft safety.

***2.Assessing Environmental and Economic Impact:***

The analysis aims to quantify the financial implications of bird strikes on airlines and airports, providing insight into the cost-effectiveness of preventive measures. It also considers the environmental factors contributing to the frequency and severity of bird strikes, offering a basis for developing more sustainable aviation practices.

***3.Informing Policy and Operational Decisions:***

By detailing the effects of bird strikes at different altitudes, the impact on flights, and the extent of prior warnings provided to pilots, the study supports informed decision-making by aviation authorities, airlines, and airport operators. The insights gained can be used to refine policies, improve pilot training, and optimize operational procedures to minimize the risk and impact of bird strikes.

***4.Leveraging Technology and AI:***

The analysis underscores the potential of utilizing advanced technologies, including artificial intelligence (AI) and Multi-Agent Systems (MAS), to predict, detect, and prevent bird strikes. By doing so, it highlights the role of innovation in creating safer and more resilient aviation systems.

In summary, this analysis is a critical step towards enhancing aviation safety, reducing economic losses, and promoting the adoption of cutting-edge technologies in managing and mitigating the risks associated with bird strikes.

# **GitHub Link -**

# **Problem Statement**

Transport and communication are in the crucial domain in the field of analytics.
Environmental impacts and safety are, nowadays, two major concerns of the scientific
community with respect to transport scenarios and to the ever-growing urban areas.
These issues gain more importance due to the increasing amount of vehicles and
people. Seeking new solutions is reaching a point where available technologies and
artificial intelligence, especially MAS, are being recognized as ways to cope with and
tackle these kinds of problems in a distributed and more appropriate way.
A bird strike is strictly defined as a collision between a bird and an aircraft which is in
flight or on a take-off or landing roll. The term is often expanded to cover other wildlife
strikes - with bats or ground animals. Bird Strike is common and can be a significant
threat to aircraft safety. For smaller aircraft, significant damage may be caused to the
aircraft structure and all aircraft, especially jet-engine ones, are vulnerable to the loss
of thrust which can follow the ingestion of birds into engine air intakes. This has
resulted in several fatal accidents.
Bird strikes may occur during any phase of flight, but are most likely during the
take-off, initial climb, approach and landing phases due to the greater numbers of birds
in flight at lower levels. To have a closer look the following document visually depicts
the data collected on Bird Strikes by FAA between 2000-2011.

***Case Studies***

● Visuals Depicting the Number of Bird Strikes

● Yearly Analysis & Bird Strikes in the US

● Top 10 US Airlines in terms of having encountered bird strikes

● Airports with most incidents of bird strikes – Top 50

● Yearly Cost Incurred due to Bird Strikes

● When do most bird strikes occur?

● Altitude of aeroplanes at the time of strike

● Phase of flight at the time of the strike.

● Average Altitude of the aeroplanes in different phases at the
time of strike
● Effect of Bird Strikes & Impact on Flight

● Effect of Strike at Different Altitude

● Were Pilots Informed? & Prior Warning and Effect of Strike Relation

# ***Let's Begin !***

### Import Libraries

In [4]:
# Importing necessary libraries

import pandas as pd
import numpy as np
from datetime import datetime

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# This is used to suppress or ignore all warnings in a Python script.
import warnings
warnings.filterwarnings('ignore')

### Dataset Loading

In [5]:
# Mounting Drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
# Load Dataset

Data = pd.read_excel("/content/drive/MyDrive/Unified mentor projects/MY PROJECT/Bird Strike 2000 - 2011/Bird Strikes data.xlsx")

### Dataset First View

In [8]:
Data.head().T

,0,1,2,3,4
Record ID,202152,208159,207601,215953,219878
Aircraft: Type,Airplane,Airplane,Airplane,Airplane,Airplane
Airport: Name,LAGUARDIA NY,DALLAS/FORT WORTH INTL ARPT,LAKEFRONT AIRPORT,SEATTLE-TACOMA INTL,NORFOLK INTL
Altitude bin,> 1000 ft,< 1000 ft,< 1000 ft,< 1000 ft,< 1000 ft
Aircraft: Make/Model,B-737-400,MD-80,C-500,B-737-400,CL-RJ100/200
Wildlife: Number struck,Over 100,Over 100,Over 100,Over 100,Over 100
Wildlife: Number Struck Actual,859,424,261,806,942
Effect: Impact to flight,Engine Shut Down,NaN,NaN,Precautionary Landing,NaN
FlightDate,2000-11-23 00:00:00,2001-07-25 00:00:00,2001-09-14 00:00:00,2002-09-05 00:00:00,2003-06-23 00:00:00
Effect: Indicated Damage,Caused damage,Caused damage,No damage,No damage,No damage
Aircraft: Number of engines?,2,2,2,2,2
Aircraft: Airline/Operator,US AIRWAYS*,AMERICAN AIRLINES,BUSINESS,ALASKA AIRLINES,COMAIR AIRLINES
Origin State,New York,Texas,Louisiana,Washington,Virginia
When: Phase of flight,Climb,Landing Roll,Approach,Climb,Approach
Conditions: Precipitation,NaN,NaN,NaN,NaN,NaN
Remains of wildlife collected?,False,False,False,True,False
Remains of wildlife sent to Smithsonian,False,False,False,False,False
Remarks,FLT 753. PILOT REPTD A HUNDRED BIRDS ON UNKN T...,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",NO DMG REPTD.
Wildlife: Size,Medium,Small,Small,Small,Small
Conditions: Sky,No Cloud,Some Cloud,No Cloud,Some Cloud,No Cloud
Wildlife: Species,Unknown bird - medium,Rock pigeon,European starling,European starling,European starling
Pilot warned of birds or wildlife?,N,Y,N,Y,N
Cost: Total $,30736,0,0,0,0
Feet above ground,1500.0,0.0,50.0,50.0,50.0
Number of people injured,0,0,0,0,0
Is Aircraft Large?,Yes,No,No,Yes,No

### Dataset Rows & Columns count

In [10]:
Data.shape

(25558, 26)

In [11]:
# Describe the dataset

Data.describe()

,Record ID,Wildlife: Number Struck Actual,FlightDate,Cost: Total $,Feet above ground,Number of people injured
count,25558.000000,25558.000000,25429,2.555800e+04,25429.000000,25558.000000
mean,253916.085609,2.691525,2007-01-22 13:20:40.017303040,5.567354e+03,799.028432,0.001056
min,1195.000000,1.000000,2000-01-02 00:00:00,0.000000e+00,0.000000,0.000000
25%,225783.750000,1.000000,2004-06-17 00:00:00,0.000000e+00,0.000000,0.000000
50%,248749.000000,1.000000,2007-07-29 00:00:00,0.000000e+00,50.000000,0.000000
75%,269168.750000,1.000000,2009-11-01 00:00:00,0.000000e+00,700.000000,0.000000
max,321909.000000,942.000000,2011-12-31 00:00:00,1.239775e+07,18000.000000,6.000000
std,38510.453382,12.793975,NaN,1.219713e+05,1740.079843,0.050420

### Dataset Information

In [12]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25558 entries, 0 to 25557
Data columns (total 26 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Record ID                                25558 non-null  int64
 1   Aircraft: Type                           25429 non-null  object
 2   Airport: Name                            25429 non-null  object
 3   Altitude bin                             25429 non-null  object
 4   Aircraft: Make/Model                     25558 non-null  object
 5   Wildlife: Number struck                  25429 non-null  object
 6   Wildlife: Number Struck Actual           25558 non-null  int64
 7   Effect: Impact to flight                 2078 non-null   object
 8   FlightDate                               25429 non-null  datetime64[ns]
 9   Effect: Indicated Damage                 25558 non-null  object
 10  Aircraft: Number of engines?             25291 non-null  object
 11  Aircraft: Airline/Operator               25429 non-null  object
 12  Origin State                             25109 non-null  object
 13  When: Phase of flight                    25429 non-null  object
 14  Conditions: Precipitation                2015 non-null   object
 15  Remains of wildlife collected?           25558 non-null  bool
 16  Remains of wildlife sent to Smithsonian  25558 non-null  bool
 17  Remarks                                  20787 non-null  object
 18  Wildlife: Size                           25429 non-null  object
 19  Conditions: Sky                          25558 non-null  object
 20  Wildlife: Species                        25558 non-null  object
 21  Pilot warned of birds or wildlife?       25429 non-null  object
 22  Cost: Total $                            25558 non-null  int64
 23  Feet above ground                        25429 non-null  float64
 24  Number of people injured                 25558 non-null  int64
 25  Is Aircraft Large?                       25429 non-null  object
dtypes: bool(2), datetime64[ns](1), float64(1), int64(4), object(18)
memory usage: 4.7+ MB

#### Duplicate Values

In [13]:
# Remove Duplicate Value in Dataset

Data.drop_duplicates(inplace = True)

In [14]:
Data.shape

(25558, 26)

Dataframe shape remain same that means there is no duplicate values in our Dataset